### ISSUE TITLE
Unable to find CyUSB Driver

### ISSUE THREAD

**Issue by hsm-0510** [tomojitakasu/PocketSDR#19]
For windows installation, the driver installation link you mentioned in PocketSDR/driver/readme.txt no longer has the download available, can you mention an updated link to the driver installation?
![image](https://github.com/user-attachments/assets/0cb4e367-1a3f-4e86-bc40-493032d57710)

**Comment by tomojitakasu** [comment]
The old page might be moved or deleted.

Please refer the following page and download EZ-USB FX3 SDK. The SDK includes drivers supporting EZ-USB FX2LP and FX3.

https://www.infineon.com/cms/en/design-support/tools/sdk/usb-controllers-sdk/ez-usb-fx3-software-development-kit/
