### ISSUE TITLE
RTKLib RTCM3 signal code mapping extension for GLONAS

### ISSUE THREAD

**Issue by ourairquality** [tomojitakasu/PocketSDR#28]
Noted the updated extensions to the RTCM3 mapping tables in lib/RTKLIB/src/rtcm3.c and that this table appears to differ significantly from that of BNC which has the following mapping for GLONASS. All the other extensions appear to be consistent with BNC, rtcm3.c includes more signals but there are no conflicts. Could I ask if these were intended to follow some standard or were they chosen arbitrarily?

BNC_2.13.1/src/RTCM3/RTCM3Decoder.cpp has the signal mappings, which would map to the following for rtcm3.c

const char *msm_sig_glo[32] = {
    "",   "1C", "1P", "",   "",   "",   "", "2C", "2P", "4A", "4B", "4X",  //  1-12
    "6A", "6B", "6X", "3I", "3Q", "3X", "", "",   "",   "",   "",   "",    // 13-24
    "",   "",   "",   "",   "",   "",   "", ""};                           // 25-32

**Comment by tomojitakasu** [comment]
As far as I know, the current RTCM 3 standard has not yet supported GLONASS L1OC, L2OC and L3OC.
The code ID assignment of these signals is just tentative without any basis.
