### ISSUE TITLE
Missing Drivers for Windows Installation

### ISSUE THREAD

**Issue by CCV-ESA** [tomojitakasu/PocketSDR#31]
Hello everyone!

I am trying to install the Windows driver for Pocket SDR, following the steps presented in the readme.
However, there is a problem with missing files. Following the link that should direct me to where the Drivers.zip archive is found, I am met on Infineon's website with a message that tells that the page is archived.

I've managed to get the archive thanks to wayback machine, but it seems to be empty.

Would it be possible to confirm that getting a newer version of EZ-USB FXL2P driver should work or provide the drivers that should be included in the missing archive?

**Comment by tomojitakasu** [comment]
Refer Issue #19.

https://github.com/tomojitakasu/PocketSDR/issues/19
